# Generated by Django 4.2.3 on 2023-07-12 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_remove_categoria_descripcion_remove_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
