# Generated by Django 4.2.3 on 2023-07-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0005_categoria_activo_categoria_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
