# Generated by Django 4.2.3 on 2023-07-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0006_articulo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='text',
            field=models.TextField(),
        ),
    ]
