# Generated by Django 4.2.3 on 2023-07-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0011_alter_articulo_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fecha_publicacion',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='creacion',
        ),
    ]
