# Generated by Django 4.2.3 on 2023-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Colaborador', 'Colaborador'), ('Visitante', 'Visitante'), ('Miembro', 'Miembro'), ('Superusuario', 'Superusuario')], default='Miembro', max_length=20),
        ),
    ]
